// Row types matching supabase/migrations/20260604000001_init.sql.
//
// Two files coexist:
//   - `supabase.generated.ts` — auto-generated by `npx supabase gen types
//     typescript --linked`. The canonical schema dump from the live DB.
//     Regenerate after every migration. Types are loosely typed (e.g.
//     `severity: string` instead of the enum).
//   - `supabase.ts` (this file) — hand-maintained, encodes the CHECK-
//     constraint enums as literal unions so the mappers get tight typing
//     end-to-end. Update this file alongside any schema change.
//
// If the two drift, the mappers will fail to compile against the generated
// types — that's the intended forcing function. Run:
//   npx supabase gen types typescript --linked | Out-File -Encoding utf8 \
//     src/types/supabase.generated.ts
// after every migration and reconcile this file as needed.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type MarketType =
  | "Stocks"
  | "Options"
  | "Futures"
  | "Forex"
  | "Crypto";
export type TradeDirection = "Long" | "Short";
export type SessionType = "premarket" | "regular" | "afterhours" | "custom";
export type SessionStatus = "active" | "closed";
export type TradeStatus = "active" | "closed";
export type TradeApprovalStatus = "approved" | "approved_with_warnings";
export type TradeExitOutcome = "win" | "loss" | "breakeven";
export type TradeExitReason =
  | "target_hit"
  | "stop_loss_hit"
  | "manual_exit_risk_reduction"
  | "manual_exit_profit_protection"
  | "manual_exit_thesis_failed"
  | "manual_exit_emotional"
  | "end_of_day_exit"
  | "other";
export type DeviationSeverity = "info" | "caution" | "elevated" | "critical";
export type BehaviorSeverity = "info" | "warning" | "fail";
export type BehaviorSource = "trade_desk" | "rules_risk" | "journal" | "system";
export type BehaviorDecision =
  | "approved"
  | "cancel_trade"
  | "revise_trade"
  | "continue_anyway";
export type InterventionDecision =
  | "continue_anyway"
  | "revise_trade"
  | "cancel_trade";
export type InterventionEventType =
  | "intervention_cancel_trade"
  | "intervention_revise_trade"
  | "intervention_continue_anyway";
export type InterventionSeverity = "warning" | "violation";
export type ValidationStatus = "approved" | "warning" | "violation";
export type SessionNoteCategory =
  | "general"
  | "behavior"
  | "strategy"
  | "mindset";
export type AccountCurrency = "USD" | "EUR" | "GBP" | "CAD";
export type AccountType = "Cash" | "Margin" | "Futures" | "Crypto";
export type WarningLevel = "soft" | "standard" | "strict" | "hard_lock";
export type UserPlan = "trial" | "starter" | "pro" | "elite";

export interface ProfileRow {
  id: string;
  display_name: string;
  email: string;
  plan: UserPlan;
  onboarding_complete: boolean;
  onboarding_step: number;
  onboarding_completed_at: string | null;
  selected_markets: MarketType[];
  // Qualitative onboarding baseline (mindset, risk tolerance, triggers).
  // Nested/evolving shape → JSONB.
  behavioral_baseline: Record<string, unknown>;
  migrated_from_local_at: string | null;
  created_at: string;
  updated_at: string;
}
export type ProfileInsert = Partial<ProfileRow> & { id: string };
export type ProfileUpdate = Partial<ProfileRow>;

export interface RiskRulesRow {
  user_id: string;
  account_size: number;
  account_currency: AccountCurrency;
  account_type: AccountType;
  base_risk_per_trade_percent: number;
  max_dollar_risk_per_trade: number;
  max_daily_loss_percent: number;
  max_daily_trades: number;
  max_red_trades: number;
  max_consecutive_losses: number;
  cooldown_after_loss_minutes: number;
  require_stop_loss: boolean;
  minimum_reward_risk: number;
  max_position_size: number;
  max_adds_per_trade: number;
  max_open_positions: number;
  no_averaging_down: boolean;
  setup_must_be_approved: boolean;
  allowed_setups: string[];
  no_reentry_within_minutes: number;
  no_revenge_trading: boolean;
  no_trading_after_emotional_warning: boolean;
  no_trades_outside_allowed_setups: boolean;
  no_overtrading: boolean;
  warning_level: WarningLevel;
  require_confirmation_before_override: boolean;
  reflection_prompt_after_override: boolean;
  lockout_after_max_loss: boolean;
  // Per-market risk fields with no structured column (instrument unit,
  // market-specific caps, raw rule-toggle ids). Core risk values use the
  // typed columns above. → JSONB.
  market_config: Record<string, unknown>;
  updated_at: string;
}
export type RiskRulesInsert = Partial<RiskRulesRow> & { user_id: string };
export type RiskRulesUpdate = Partial<RiskRulesRow>;

export interface TradingSessionRow {
  id: string;
  user_id: string;
  client_id: string | null;
  trading_date: string;
  session_type: SessionType;
  custom_label: string | null;
  status: SessionStatus;
  started_at: string;
  ended_at: string | null;
  closed_daily_loss_used_percent: number | null;
  closed_trades_taken: number | null;
  closed_red_trades: number | null;
  closed_consecutive_losses: number | null;
  closed_daily_loss_breached: boolean | null;
  created_at: string;
  updated_at: string;
}
export type TradingSessionInsert = Omit<
  Partial<TradingSessionRow>,
  "id" | "created_at" | "updated_at"
> & {
  user_id: string;
  trading_date: string;
};
export type TradingSessionUpdate = Partial<TradingSessionRow>;

export interface TradeRow {
  id: string;
  user_id: string;
  client_id: string | null;
  session_id: string | null;
  trading_date: string;
  symbol: string;
  market_type: MarketType;
  direction: TradeDirection;
  setup_type: string;
  entry_price: number;
  stop_price: number | null;
  target_price: number | null;
  position_size: number;
  trade_plan: string;
  approved_at: string;
  activated_at: string;
  original_risk: number | null;
  account_risk_percent: number | null;
  reward_risk_ratio: number | null;
  current_stop_price: number | null;
  current_target_price: number | null;
  current_position_size: number;
  current_avg_entry: number;
  current_risk: number | null;
  current_account_risk_percent: number | null;
  current_reward_risk_ratio: number | null;
  mistake_flagged: boolean;
  mistake_note: string | null;
  closed_at: string | null;
  exit_price: number | null;
  exit_outcome: TradeExitOutcome | null;
  realized_pnl: number | null;
  realized_r: number | null;
  exit_reflection: string | null;
  exit_reason: TradeExitReason | null;
  exit_notes: string | null;
  loss_reduced: boolean | null;
  loss_reduction_amount: number | null;
  loss_reduction_percent: number | null;
  approval_status: TradeApprovalStatus;
  approval_warnings: Json;
  override_accepted: boolean;
  status: TradeStatus;
  source: string;
  deviation_count: number;
  mistake_count: number;
  created_at: string;
  updated_at: string;
}
export type TradeInsert = Omit<
  Partial<TradeRow>,
  "id" | "created_at" | "updated_at"
> & {
  user_id: string;
  trading_date: string;
  symbol: string;
  market_type: MarketType;
  direction: TradeDirection;
  entry_price: number;
  position_size: number;
  approved_at: string;
  activated_at: string;
  current_position_size: number;
  current_avg_entry: number;
};
export type TradeUpdate = Partial<TradeRow>;

export interface TradeMonitoringEventRow {
  id: string;
  user_id: string;
  client_id: string | null;
  trade_id: string;
  session_id: string | null;
  trading_date: string | null;
  timestamp: string;
  update: Json;
  deviations: Json;
  severity: DeviationSeverity;
  recommendations: Json;
  created_at: string;
}
export type TradeMonitoringEventInsert = Omit<
  Partial<TradeMonitoringEventRow>,
  "id" | "created_at"
> & {
  user_id: string;
  trade_id: string;
  timestamp: string;
  update: Json;
  severity: DeviationSeverity;
};

export interface BehaviorEventRow {
  id: string;
  user_id: string;
  client_id: string | null;
  session_id: string | null;
  trade_id: string | null;
  trading_date: string | null;
  event_type: string;
  display_title: string;
  display_description: string;
  source: BehaviorSource;
  symbol: string | null;
  setup_type: string | null;
  direction: TradeDirection | null;
  decision: BehaviorDecision | null;
  severity: BehaviorSeverity;
  triggered_rules: Json;
  total_risk: number | null;
  account_risk_percent: number | null;
  metadata: Json;
  timestamp: string;
  created_at: string;
}
export type BehaviorEventInsert = Omit<
  Partial<BehaviorEventRow>,
  "id" | "created_at"
> & {
  user_id: string;
  event_type: string;
  display_title: string;
  source: BehaviorSource;
  severity: BehaviorSeverity;
  timestamp: string;
};

export interface InterventionRow {
  id: string;
  user_id: string;
  client_id: string | null;
  session_id: string | null;
  behavior_event_id: string | null;
  trading_date: string | null;
  timestamp: string;
  decision: InterventionDecision;
  event_type: InterventionEventType;
  severity: InterventionSeverity;
  symbol: string | null;
  market_type: MarketType | null;
  direction: TradeDirection | null;
  setup_type: string | null;
  entry_price: number | null;
  stop_price: number | null;
  target_price: number | null;
  position_size: number | null;
  account_size: number | null;
  total_risk: number | null;
  account_risk_percent: number | null;
  reward_risk_ratio: number | null;
  validation_status: ValidationStatus | null;
  triggered_rules: Json;
  warning_count: number | null;
  violation_count: number | null;
  source: string;
  created_at: string;
}
export type InterventionInsert = Omit<
  Partial<InterventionRow>,
  "id" | "created_at"
> & {
  user_id: string;
  decision: InterventionDecision;
  event_type: InterventionEventType;
  severity: InterventionSeverity;
  timestamp: string;
};

export interface SessionNoteRow {
  id: string;
  user_id: string;
  client_id: string | null;
  session_id: string | null;
  trading_date: string | null;
  content: string;
  category: SessionNoteCategory;
  created_at: string;
}
export type SessionNoteInsert = Omit<
  Partial<SessionNoteRow>,
  "id" | "created_at"
> & {
  user_id: string;
  content: string;
};

export interface DailyReflectionRow {
  id: string;
  user_id: string;
  session_id: string | null;
  trading_date: string;
  answers: Json;
  emotional_notes: string;
  freeform_notes: string;
  summary: Json;
  insight: string;
  tomorrow_focus: string;
  saved_at: string;
  created_at: string;
  updated_at: string;
}
export type DailyReflectionInsert = Omit<
  Partial<DailyReflectionRow>,
  "id" | "created_at" | "updated_at"
> & {
  user_id: string;
  trading_date: string;
};
export type DailyReflectionUpdate = Partial<DailyReflectionRow>;

export interface TradeReflectionRow {
  id: string;
  user_id: string;
  trade_id: string;
  trading_date: string | null;
  answers: Json;
  saved_at: string;
  created_at: string;
  updated_at: string;
}
export type TradeReflectionInsert = Omit<
  Partial<TradeReflectionRow>,
  "id" | "created_at" | "updated_at"
> & {
  user_id: string;
  trade_id: string;
};
export type TradeReflectionUpdate = Partial<TradeReflectionRow>;
