export type LibrarySetup = { id: string; label: string };
export type LibraryCategory = {
  id: string;
  label: string;
  setups: LibrarySetup[];
};

export const SETUP_LIBRARY: LibraryCategory[] = [
  {
    id: "momentum-breakouts",
    label: "Momentum & Breakouts",
    setups: [
      { id: "lib-momentum-breakout", label: "Momentum Breakout" },
      { id: "lib-orb", label: "Opening Range Breakout (ORB)" },
      { id: "lib-hod-break", label: "High of Day Break" },
      { id: "lib-daily-level-breakout", label: "Daily Level Breakout" },
      { id: "lib-gap-and-go", label: "Gap and Go" },
      { id: "lib-trend-continuation", label: "Trend Continuation" },
      { id: "lib-bull-flag", label: "Bull Flag" },
      { id: "lib-bear-flag", label: "Bear Flag" },
      { id: "lib-flat-top-breakout", label: "Flat Top Breakout" },
      { id: "lib-volume-expansion", label: "Volume Expansion Breakout" },
      { id: "lib-multi-day-breakout", label: "Multi-Day Breakout" },
      { id: "lib-premarket-breakout", label: "Pre-Market Breakout" },
      { id: "lib-vwap-breakout", label: "VWAP Breakout" },
      { id: "lib-ema-reclaim", label: "EMA Reclaim" },
      { id: "lib-micro-pullback", label: "Micro Pullback" },
      { id: "lib-range-expansion", label: "Range Expansion" },
    ],
  },
  {
    id: "pullbacks-trend",
    label: "Pullbacks & Trend Entries",
    setups: [
      { id: "lib-vwap-pullback", label: "VWAP Pullback" },
      { id: "lib-ema-pullback", label: "EMA Pullback" },
      { id: "lib-first-pullback", label: "First Pullback" },
      { id: "lib-trend-pullback", label: "Trend Pullback" },
      { id: "lib-support-bounce", label: "Support Bounce" },
      { id: "lib-resistance-reject", label: "Resistance Reject" },
      { id: "lib-higher-low-entry", label: "Higher Low Entry" },
      { id: "lib-lower-high-entry", label: "Lower High Entry" },
      { id: "lib-trendline-retest", label: "Trendline Retest" },
      { id: "lib-breakout-retest", label: "Breakout Retest" },
      { id: "lib-ma-reclaim", label: "Moving Average Reclaim" },
      { id: "lib-trend-continuation-pullback", label: "Trend Continuation Pullback" },
    ],
  },
  {
    id: "mean-reversion",
    label: "Mean Reversion & Reversals",
    setups: [
      { id: "lib-mean-reversion", label: "Mean Reversion" },
      { id: "lib-exhaustion-reversal", label: "Exhaustion Reversal" },
      { id: "lib-parabolic-reversal", label: "Parabolic Reversal" },
      { id: "lib-gap-fill", label: "Gap Fill" },
      { id: "lib-oversold-bounce", label: "Oversold Bounce" },
      { id: "lib-overbought-rejection", label: "Overbought Rejection" },
      { id: "lib-failed-breakdown", label: "Failed Breakdown" },
      { id: "lib-failed-breakout", label: "Failed Breakout" },
      { id: "lib-double-bottom-reversal", label: "Double Bottom Reversal" },
      { id: "lib-double-top-reversal", label: "Double Top Reversal" },
      { id: "lib-vwap-reclaim", label: "VWAP Reclaim" },
      { id: "lib-reversal-key-level", label: "Reversal at Key Level" },
      { id: "lib-dead-cat-bounce", label: "Dead Cat Bounce" },
      { id: "lib-capitulation-reversal", label: "Capitulation Reversal" },
    ],
  },
  {
    id: "chart-patterns",
    label: "Chart Patterns",
    setups: [
      { id: "lib-ascending-triangle", label: "Ascending Triangle" },
      { id: "lib-descending-triangle", label: "Descending Triangle" },
      { id: "lib-symmetrical-triangle", label: "Symmetrical Triangle" },
      { id: "lib-wedge", label: "Wedge Pattern" },
      { id: "lib-cup-and-handle", label: "Cup and Handle" },
      { id: "lib-head-shoulders", label: "Head and Shoulders" },
      { id: "lib-inv-head-shoulders", label: "Inverse Head and Shoulders" },
      { id: "lib-channel-break", label: "Channel Break" },
      { id: "lib-rectangle-consolidation", label: "Rectangle Consolidation" },
      { id: "lib-pennant", label: "Pennant Formation" },
      { id: "lib-abcd", label: "ABCD Pattern" },
      { id: "lib-compression-breakout", label: "Compression Breakout" },
    ],
  },
  {
    id: "catalyst-volatility",
    label: "Catalyst & Volatility",
    setups: [
      { id: "lib-earnings-runner", label: "Earnings Runner" },
      { id: "lib-news-catalyst", label: "News Catalyst" },
      { id: "lib-fda-catalyst", label: "FDA Catalyst" },
      { id: "lib-analyst-rating", label: "Analyst Upgrade/Downgrade" },
      { id: "lib-sympathy-play", label: "Sympathy Play" },
      { id: "lib-sector-momentum", label: "Sector Momentum" },
      { id: "lib-rvol-spike", label: "Relative Volume Spike" },
      { id: "lib-short-squeeze", label: "Short Squeeze" },
      { id: "lib-float-rotation", label: "Float Rotation" },
      { id: "lib-halt-resume", label: "Halt Resume Setup" },
      { id: "lib-breaking-news", label: "Breaking News Momentum" },
      { id: "lib-ipo-momentum", label: "IPO Momentum" },
    ],
  },
  {
    id: "futures-options",
    label: "Futures / Options Specific",
    setups: [
      { id: "lib-opening-drive", label: "Opening Drive" },
      { id: "lib-trend-day-continuation", label: "Trend Day Continuation" },
      { id: "lib-fut-range-expansion", label: "Range Expansion" },
      { id: "lib-liquidity-sweep", label: "Liquidity Sweep" },
      { id: "lib-vwap-trend-trade", label: "VWAP Trend Trade" },
      { id: "lib-gamma-squeeze", label: "Gamma Squeeze" },
      { id: "lib-0dte-momentum", label: "0DTE Momentum" },
      { id: "lib-fut-reversal-level", label: "Futures Reversal at Level" },
      { id: "lib-options-flow", label: "Options Flow Momentum" },
      { id: "lib-delta-hedging", label: "Delta Hedging Move" },
      { id: "lib-contract-sweep", label: "Contract Sweep Reaction" },
    ],
  },
];
